name: CD - Deploy to LocalStack

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies (Terraform, AWS CLI)
        run: |
          sudo apt-get update && sudo apt-get install -y unzip python3-pip
          curl -LO https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
          unzip terraform_1.5.7_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          pip install localstack-client awscli

      - name: Verify Terraform Installation
        run: terraform -version

      - name: Run LocalStack in Docker
        run: |
          docker run -d --name localstack-container \
            -p 4566:4566 -p 4510-4559:4510-4559 \
            -v /var/run/docker.sock:/var/run/docker.sock \
            localstack/localstack
          sleep 30

      - name: Initialize Terraform
        run: |
          export AWS_ACCESS_KEY_ID="test"
          export AWS_SECRET_ACCESS_KEY="test"
          export AWS_DEFAULT_REGION="us-east-1"
          terraform init

      - name: Terraform Apply
        run: |
          export AWS_ACCESS_KEY_ID="test"
          export AWS_SECRET_ACCESS_KEY="test"
          export AWS_DEFAULT_REGION="us-east-1"
          terraform apply -var-file="envs/prod.tfvars" -auto-approve

      - name: Verify S3 Bucket in LocalStack
        run: |
          awslocal s3 ls || echo "Failed to list S3 buckets."

      - name: Terraform Destroy
        if: always()
        run: |
          export AWS_ACCESS_KEY_ID="test"
          export AWS_SECRET_ACCESS_KEY="test"
          export AWS_DEFAULT_REGION="us-east-1"
          terraform destroy -var-file="envs/prod.tfvars" -auto-approve

      - name: Stop LocalStack
        if: always()
        run: |
          docker stop localstack-container || echo "LocalStack not running."
          docker rm localstack-container || echo "LocalStack already removed."
