name: Python Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/crawler/requirements.txt
        pip install -r src/graph/requirements.txt
        pip install -r src/api/requirements.txt

    - name: Run tests for crawler
      run: |
        python -m unittest discover -s src/crawler/tests_crawler

    - name: Run tests for graph
      run: |
        python -m unittest discover -s src/graph/tests_graph

    - name: Run tests for api
      run: |
        python -m unittest discover -s src/api/tests_api
